### ISSUE TITLE
Change MTIDs to include page number

### ISSUE THREAD

**Issue by bmschmidt** [massivetexts/compare-tools#2]
Problem: we don't have page numbers associated with the chunking. They're useful:

1. Linking directly to pages in Hathi using a sequence number
2. Deciding what pages to include in a page-wise comparison after chunks have been identified.

There are other solutions for this (some other file floating around), but I think the simplest would be to have MTIDs include page numbers. 

So instead of: `aeu.ark:/13960/t0000vt1c-0002`,
use the format `aeu.ark:/13960/t0000vt1c-0002-12-7`,
where the zero-padded sequential id is the same, but the two additional characters indicate
1. The starting page
2. The number of pages in the chunk. So 12-7 indicates that it runs from pages 12 to 18. (Note: not 19, which could potentially be confusing.)

The second element could also be the ending page; this approach saves a few bytes at the expense of requiring you to do some addition that could be a little confusing.

## Questions

1. Should it be `0002-12-18` instead of `0002-12-7`?
2. Should it use a different delimiter? I think the current approach is best, because you can say
`htid, seq, start_page, pages = mtid.split('-')`.

**Comment by bmschmidt** [comment]
Agreed in meeting to use `0002-12-18` format instead of `0002-12-7`

**Comment by organisciak** [comment]
Q1: Option A (use end page)
Q2 - Use `-`

**Comment by bmschmidt** [comment]
Peter will check into the feature reader.

**Comment by organisciak** [comment]
HTRC Feature Reader code at https://github.com/massivetexts/htrc-feature-reader/commit/5d2e5241af8aa35a3165714398729f0efb55d363. When exporting chunks, the pages are kept as integers. Downstream we can concatenate into the MTID strings. Note that the default is to not include the page reference, you need to pass `page_ref=True` to `chunked_tokenlist()`

e.g. 

`vol.chunked_tokenlist(page_ref=True)`

```
				count
chunk	pstart	pend	lowercase	
1	2	43	!	10
			"	478
			"broken	1
			"do	1
			"drapin	1
...
```

I'll update our other code before this issue can be closed.

**Comment by organisciak** [comment]
One hitch is that having predictably iterating names is convenient when you don't know how many chunks there are in an HTID. In `SRP.Vector_file`, I'm finding it useful to iterate `'{}-{:04d}'.format(htid, i)` until a KeyError.

With the new format, the start is still predictable. Would you be open to a startswith retrieval function in `Vector_file`, perhaps? I haven't gone back to the MTAnnoy code yet, but likely that will require some thought also.

The alternative is preserving the pstart and pend information separately, rather than in the MTID. Since I'm pre-processing chunked files, the files on disk can be look like the `chunked_tokenlist(page_ref=True)` example above.

**Comment by bmschmidt** [comment]
Sure, open to startswith. I see two ways to go:

1. file.iter(start_key = "foo", start_row = 13). Block so that only one of these can be filled out. Use the same code as 'iter', return an iterator over (id, vector) tuples.
2. Allow file['foo'] to optionally take not a string or list arg but a compiled regex or list of regexen. file[re.compile('hvd.6453225.*')]. Also an iterator over (id, row) tuples; I feel OK because it's already not typesafe. Internally this would iter over the cache keys, test regex, yield a string-based getitem. I think the second might be more useful and bloat things less.

I have a preference for the second if the performance hit isn't terrible. 

You personally could also access the first row and then keep calling file._read_binary_row() just like `.__iter__()` does internally.

**Comment by bmschmidt** [comment]
I've implemented strategy 2 in a [new branch on the SRP module.](https://github.com/bmschmidt/pySRP/tree/regex_keys) Performance is meh; could be as much as a second before the iteration begins. But I don't really see a general-purpose alternative. Even in this specific case, I don't see how to get the id for the first entry--you don't know the page range of the first element?

I continue to really want the pages in the IDs, I think. Makes it possible, e.g., to retrieve some set MTIDs in an observable notebook and then link straight to the Hathi pages.

The separate-file strategy could also be used in the performance optimized step; load up a list of all the chunks for a given ID, and then use that to accelerate dictionary-based queries.

**Comment by bmschmidt** [comment]
Moving on with this change in the hathi-test-dataset repo.

**Comment by bmschmidt** [comment]
Completed--see larger discussion in https://github.com/massivetexts/compare-tools/issues/11
